{"links": {"self": {"href": "data/repositories/labscript_suite/lyse/issues/45/comments/49125481.json"}, "html": {"href": "#!/labscript_suite/lyse/issues/45#comment-49125481"}}, "issue": {"links": {"self": {"href": "data/repositories/labscript_suite/lyse/issues/45.json"}}, "type": "issue", "id": 45, "repository": {"links": {"self": {"href": "data/repositories/labscript_suite/lyse.json"}, "html": {"href": "#!/labscript_suite/lyse"}, "avatar": {"href": "data/bytebucket.org/ravatar/{55eebdfe-43d1-4ae8-9049-50c55b295397}ts=249921"}}, "type": "repository", "name": "lyse", "full_name": "labscript_suite/lyse", "uuid": "{55eebdfe-43d1-4ae8-9049-50c55b295397}"}, "title": "Dataframe stopped updating after multishot routine error"}, "content": {"raw": "Seems pretty odd. Looking at the code that communicates the updated data back to the dataframe, and the code that updates the dataframe, nothing jumps out to me that would explain the lack up updating given that surrounding code seems to be running and not crashing. I'll keep an eye out for it though, if anyone figures out how to reproduce it we can debug it properly.", "markup": "markdown", "html": "<p>Seems pretty odd. Looking at the code that communicates the updated data back to the dataframe, and the code that updates the dataframe, nothing jumps out to me that would explain the lack up updating given that surrounding code seems to be running and not crashing. I'll keep an eye out for it though, if anyone figures out how to reproduce it we can debug it properly.</p>", "type": "rendered"}, "created_on": "2018-11-26T16:02:11.824446+00:00", "user": {"display_name": "Chris Billington", "uuid": "{e363c5a9-5075-4656-afb5-88bd6a6dceeb}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D"}, "html": {"href": "https://bitbucket.org/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/9238baf7300c41c0e7294db922899e6ad=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsCB-1.png"}}, "nickname": "cbillington", "type": "user", "account_id": "557058:cbf1bc43-1dc2-477b-9e25-1a8f40fd7ee3"}, "updated_on": null, "type": "issue_comment", "id": 49125481}