{"links": {"self": {"href": "data/repositories/labscript_suite/lyse/pullrequests/21/comments/41300413.json"}, "html": {"href": "#!/labscript_suite/lyse/pull-requests/21/_/diff#comment-41300413"}}, "parent": {"id": 41299535, "links": {"self": {"href": "data/repositories/labscript_suite/lyse/pullrequests/21/comments/41299535.json"}, "html": {"href": "#!/labscript_suite/lyse/pull-requests/21/_/diff#comment-41299535"}}}, "deleted": false, "pullrequest": {"type": "pullrequest", "id": 21, "links": {"self": {"href": "data/repositories/labscript_suite/lyse/pullrequests/21.json"}, "html": {"href": "#!/labscript_suite/lyse/pull-requests/21"}}, "title": "Close all unclosed branches"}, "content": {"raw": "Ok more testing revealed new problems. When reloading a shot that has results from such a non ascii file you get this error:\n\n\n```\n#!python\n\nTraceback (most recent call last):\n  File \"/Users/janwerkmann/anaconda/lib/python2.7/threading.py\", line 754, in run\n    self.__target(*self.__args, **self.__kwargs)\n  File \"/Users/janwerkmann/anaconda/lib/python2.7/site-packages/zprocess/__init__.py\", line 67, in f\n    six.reraise(type, value, traceback)\n  File \"/Users/janwerkmann/labscript_suite/lyse/__main__.py\", line 1671, in incoming_buffer_loop\n    dataframe = get_dataframe_from_shot(filepath)\n  File \"/Users/janwerkmann/labscript_suite/lyse/dataframe_utilities.py\", line 118, in get_dataframe_from_shot\n    flat_dict = flatten_dict(nested_dict)\n  File \"/Users/janwerkmann/labscript_suite/lyse/dataframe_utilities.py\", line 80, in flatten_dict\n    flat = flatten_dict(dictionary[name], keys=keys + (str(name),))\nUnicodeEncodeError: 'ascii' codec can't encode character u'\\xe4' in position 5: ordinal not in range(128)\n\n```\n\nSo we should better fix this first otherwise people can't open their files anymore.\nIf you want I can provide you with a h5 file that has the problem.\n\n\nWhen editing dataframe_utilities.py you could also add two lines to asdatetime that make the function python 3 compatible:\n\n```\n#!python\n\ndef asdatetime(timestr):\n    tz = tzlocal.get_localzone().zone\n    if isinstance(timestr, bytes):\n        timestr = timestr.decode('utf-8')\n    return pandas.Timestamp(timestr, tz=tz)\n```\n\nMost of dataframe_utilities doesn't seem to like python3 I'm getting a lot of errors there concerning bytes and unicode. But thats not related to this pull request.", "markup": "markdown", "html": "<p>Ok more testing revealed new problems. When reloading a shot that has results from such a non ascii file you get this error:</p>\n<div class=\"codehilite language-python\"><pre><span></span><span class=\"n\">Traceback</span> <span class=\"p\">(</span><span class=\"n\">most</span> <span class=\"n\">recent</span> <span class=\"n\">call</span> <span class=\"n\">last</span><span class=\"p\">):</span>\n  <span class=\"n\">File</span> <span class=\"s2\">&quot;/Users/janwerkmann/anaconda/lib/python2.7/threading.py&quot;</span><span class=\"p\">,</span> <span class=\"n\">line</span> <span class=\"mi\">754</span><span class=\"p\">,</span> <span class=\"ow\">in</span> <span class=\"n\">run</span>\n    <span class=\"bp\">self</span><span class=\"o\">.</span><span class=\"n\">__target</span><span class=\"p\">(</span><span class=\"o\">*</span><span class=\"bp\">self</span><span class=\"o\">.</span><span class=\"n\">__args</span><span class=\"p\">,</span> <span class=\"o\">**</span><span class=\"bp\">self</span><span class=\"o\">.</span><span class=\"n\">__kwargs</span><span class=\"p\">)</span>\n  <span class=\"n\">File</span> <span class=\"s2\">&quot;/Users/janwerkmann/anaconda/lib/python2.7/site-packages/zprocess/__init__.py&quot;</span><span class=\"p\">,</span> <span class=\"n\">line</span> <span class=\"mi\">67</span><span class=\"p\">,</span> <span class=\"ow\">in</span> <span class=\"n\">f</span>\n    <span class=\"n\">six</span><span class=\"o\">.</span><span class=\"n\">reraise</span><span class=\"p\">(</span><span class=\"nb\">type</span><span class=\"p\">,</span> <span class=\"n\">value</span><span class=\"p\">,</span> <span class=\"n\">traceback</span><span class=\"p\">)</span>\n  <span class=\"n\">File</span> <span class=\"s2\">&quot;/Users/janwerkmann/labscript_suite/lyse/__main__.py&quot;</span><span class=\"p\">,</span> <span class=\"n\">line</span> <span class=\"mi\">1671</span><span class=\"p\">,</span> <span class=\"ow\">in</span> <span class=\"n\">incoming_buffer_loop</span>\n    <span class=\"n\">dataframe</span> <span class=\"o\">=</span> <span class=\"n\">get_dataframe_from_shot</span><span class=\"p\">(</span><span class=\"n\">filepath</span><span class=\"p\">)</span>\n  <span class=\"n\">File</span> <span class=\"s2\">&quot;/Users/janwerkmann/labscript_suite/lyse/dataframe_utilities.py&quot;</span><span class=\"p\">,</span> <span class=\"n\">line</span> <span class=\"mi\">118</span><span class=\"p\">,</span> <span class=\"ow\">in</span> <span class=\"n\">get_dataframe_from_shot</span>\n    <span class=\"n\">flat_dict</span> <span class=\"o\">=</span> <span class=\"n\">flatten_dict</span><span class=\"p\">(</span><span class=\"n\">nested_dict</span><span class=\"p\">)</span>\n  <span class=\"n\">File</span> <span class=\"s2\">&quot;/Users/janwerkmann/labscript_suite/lyse/dataframe_utilities.py&quot;</span><span class=\"p\">,</span> <span class=\"n\">line</span> <span class=\"mi\">80</span><span class=\"p\">,</span> <span class=\"ow\">in</span> <span class=\"n\">flatten_dict</span>\n    <span class=\"n\">flat</span> <span class=\"o\">=</span> <span class=\"n\">flatten_dict</span><span class=\"p\">(</span><span class=\"n\">dictionary</span><span class=\"p\">[</span><span class=\"n\">name</span><span class=\"p\">],</span> <span class=\"n\">keys</span><span class=\"o\">=</span><span class=\"n\">keys</span> <span class=\"o\">+</span> <span class=\"p\">(</span><span class=\"nb\">str</span><span class=\"p\">(</span><span class=\"n\">name</span><span class=\"p\">),))</span>\n<span class=\"ne\">UnicodeEncodeError</span><span class=\"p\">:</span> <span class=\"s1\">&#39;ascii&#39;</span> <span class=\"n\">codec</span> <span class=\"n\">can</span><span class=\"s1\">&#39;t encode character u&#39;</span>\\<span class=\"n\">xe4</span><span class=\"s1\">&#39; in position 5: ordinal not in range(128)</span>\n</pre></div>\n\n\n<p>So we should better fix this first otherwise people can't open their files anymore.\nIf you want I can provide you with a h5 file that has the problem.</p>\n<p>When editing dataframe_utilities.py you could also add two lines to asdatetime that make the function python 3 compatible:</p>\n<div class=\"codehilite language-python\"><pre><span></span><span class=\"k\">def</span> <span class=\"nf\">asdatetime</span><span class=\"p\">(</span><span class=\"n\">timestr</span><span class=\"p\">):</span>\n    <span class=\"n\">tz</span> <span class=\"o\">=</span> <span class=\"n\">tzlocal</span><span class=\"o\">.</span><span class=\"n\">get_localzone</span><span class=\"p\">()</span><span class=\"o\">.</span><span class=\"n\">zone</span>\n    <span class=\"k\">if</span> <span class=\"nb\">isinstance</span><span class=\"p\">(</span><span class=\"n\">timestr</span><span class=\"p\">,</span> <span class=\"nb\">bytes</span><span class=\"p\">):</span>\n        <span class=\"n\">timestr</span> <span class=\"o\">=</span> <span class=\"n\">timestr</span><span class=\"o\">.</span><span class=\"n\">decode</span><span class=\"p\">(</span><span class=\"s1\">&#39;utf-8&#39;</span><span class=\"p\">)</span>\n    <span class=\"k\">return</span> <span class=\"n\">pandas</span><span class=\"o\">.</span><span class=\"n\">Timestamp</span><span class=\"p\">(</span><span class=\"n\">timestr</span><span class=\"p\">,</span> <span class=\"n\">tz</span><span class=\"o\">=</span><span class=\"n\">tz</span><span class=\"p\">)</span>\n</pre></div>\n\n\n<p>Most of dataframe_utilities doesn't seem to like python3 I'm getting a lot of errors there concerning bytes and unicode. But thats not related to this pull request.</p>", "type": "rendered"}, "created_on": "2017-07-23T12:19:05.914477+00:00", "user": {"display_name": "Jan Werkmann", "uuid": "{44c4905c-2b90-4045-a5f1-652b8e228626}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B44c4905c-2b90-4045-a5f1-652b8e228626%7D"}, "html": {"href": "https://bitbucket.org/%7B44c4905c-2b90-4045-a5f1-652b8e228626%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:a70cc9cf-684e-4849-a61a-9ade4d7218b5/07e5095a-4741-4dc0-a462-9c7d455f961d/128"}}, "nickname": "PhyNerd", "type": "user", "account_id": "557058:a70cc9cf-684e-4849-a61a-9ade4d7218b5"}, "updated_on": "2017-07-23T13:22:32.184695+00:00", "type": "pullrequest_comment", "id": 41300413}