{"pagelen": 50, "values": [{"update": {"description": "Fix two issues with delayed closing of lyse\r\n\r\n* There was a bug where if no configuration changed, Lyse.on_close_event\r\n  would not terminate the subprocesses, and then it would wait the full\r\n  two seconds before quitting (and potentially leave any non-zprocess subprocesses\r\n  running). Refactored on_close_event(), factoring out the 'are you sure' dialog\r\n  and the termination of all subprocesses into separate functions while fixing\r\n  the logic here.\r\n* When lyse was to actually quit, it called qapplication.quit() instead of .close()\r\n  on the main window. This means if running with `python -i`, lyse doesn't actually\r\n  close, as the event loop just fires back up again. Now it actally calls close(),\r\n  and this triggers the same method that caught the first close event, which knows\r\n  it's the second time it's been called because a flag has been set so actually closes.\r\n  This also has the side effect that the user clicking close twice will close\r\n  lyse regardless of the timeout (which seems fine).", "title": "Fix two issues with delayed closing of lyse", "destination": {"commit": {"hash": "e8dda2f57f68", "type": "commit", "links": {"self": {"href": "data/repositories/labscript_suite/lyse/commit/e8dda2f57f68.json"}, "html": {"href": "#!/labscript_suite/lyse/commits/e8dda2f57f68"}}}, "repository": {"links": {"self": {"href": "data/repositories/labscript_suite/lyse.json"}, "html": {"href": "#!/labscript_suite/lyse"}, "avatar": {"href": "data/bytebucket.org/ravatar/{55eebdfe-43d1-4ae8-9049-50c55b295397}ts=249921"}}, "type": "repository", "name": "lyse", "full_name": "labscript_suite/lyse", "uuid": "{55eebdfe-43d1-4ae8-9049-50c55b295397}"}, "branch": {"name": "default"}}, "reason": "", "source": {"commit": {"hash": "efe00aa15132", "type": "commit", "links": {"self": {"href": "https://api.bitbucket.org/2.0/repositories/cbillington/lyse/commit/efe00aa15132"}, "html": {"href": "#!/cbillington/lyse/commits/efe00aa15132"}}}, "repository": {"links": {"self": {"href": "https://api.bitbucket.org/2.0/repositories/cbillington/lyse"}, "html": {"href": "#!/cbillington/lyse"}, "avatar": {"href": "data/bytebucket.org/ravatar/{47c91022-279d-4058-88a8-959fe9ffb409}ts=python"}}, "type": "repository", "name": "lyse", "full_name": "cbillington/lyse", "uuid": "{47c91022-279d-4058-88a8-959fe9ffb409}"}, "branch": {"name": "bugfix"}}, "state": "MERGED", "author": {"display_name": "Chris Billington", "uuid": "{e363c5a9-5075-4656-afb5-88bd6a6dceeb}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D"}, "html": {"href": "https://bitbucket.org/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/9238baf7300c41c0e7294db922899e6ad=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsCB-1.png"}}, "nickname": "cbillington", "type": "user", "account_id": "557058:cbf1bc43-1dc2-477b-9e25-1a8f40fd7ee3"}, "date": "2019-05-10T02:14:04.412668+00:00"}, "pull_request": {"type": "pullrequest", "id": 63, "links": {"self": {"href": "data/repositories/labscript_suite/lyse/pullrequests/63.json"}, "html": {"href": "#!/labscript_suite/lyse/pull-requests/63"}}, "title": "Fix two issues with delayed closing of lyse"}}, {"update": {"description": "Fix two issues with delayed closing of lyse\r\n\r\n* There was a bug where if no configuration changed, Lyse.on_close_event\r\n  would not terminate the subprocesses, and then it would wait the full\r\n  two seconds before quitting (and potentially leave any non-zprocess subprocesses\r\n  running). Refactored on_close_event(), factoring out the 'are you sure' dialog\r\n  and the termination of all subprocesses into separate functions while fixing\r\n  the logic here.\r\n* When lyse was to actually quit, it called qapplication.quit() instead of .close()\r\n  on the main window. This means if running with `python -i`, lyse doesn't actually\r\n  close, as the event loop just fires back up again. Now it actally calls close(),\r\n  and this triggers the same method that caught the first close event, which knows\r\n  it's the second time it's been called because a flag has been set so actually closes.\r\n  This also has the side effect that the user clicking close twice will close\r\n  lyse regardless of the timeout (which seems fine).", "title": "Fix two issues with delayed closing of lyse", "destination": {"commit": {"hash": "e8dda2f57f68", "type": "commit", "links": {"self": {"href": "data/repositories/labscript_suite/lyse/commit/e8dda2f57f68.json"}, "html": {"href": "#!/labscript_suite/lyse/commits/e8dda2f57f68"}}}, "repository": {"links": {"self": {"href": "data/repositories/labscript_suite/lyse.json"}, "html": {"href": "#!/labscript_suite/lyse"}, "avatar": {"href": "data/bytebucket.org/ravatar/{55eebdfe-43d1-4ae8-9049-50c55b295397}ts=249921"}}, "type": "repository", "name": "lyse", "full_name": "labscript_suite/lyse", "uuid": "{55eebdfe-43d1-4ae8-9049-50c55b295397}"}, "branch": {"name": "default"}}, "reason": "", "source": {"commit": {"hash": "efe00aa15132", "type": "commit", "links": {"self": {"href": "https://api.bitbucket.org/2.0/repositories/cbillington/lyse/commit/efe00aa15132"}, "html": {"href": "#!/cbillington/lyse/commits/efe00aa15132"}}}, "repository": {"links": {"self": {"href": "https://api.bitbucket.org/2.0/repositories/cbillington/lyse"}, "html": {"href": "#!/cbillington/lyse"}, "avatar": {"href": "data/bytebucket.org/ravatar/{47c91022-279d-4058-88a8-959fe9ffb409}ts=python"}}, "type": "repository", "name": "lyse", "full_name": "cbillington/lyse", "uuid": "{47c91022-279d-4058-88a8-959fe9ffb409}"}, "branch": {"name": "bugfix"}}, "state": "OPEN", "author": {"display_name": "Chris Billington", "uuid": "{e363c5a9-5075-4656-afb5-88bd6a6dceeb}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D"}, "html": {"href": "https://bitbucket.org/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/9238baf7300c41c0e7294db922899e6ad=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsCB-1.png"}}, "nickname": "cbillington", "type": "user", "account_id": "557058:cbf1bc43-1dc2-477b-9e25-1a8f40fd7ee3"}, "date": "2019-05-10T02:14:03.819219+00:00"}, "pull_request": {"type": "pullrequest", "id": 63, "links": {"self": {"href": "data/repositories/labscript_suite/lyse/pullrequests/63.json"}, "html": {"href": "#!/labscript_suite/lyse/pull-requests/63"}}, "title": "Fix two issues with delayed closing of lyse"}}, {"approval": {"date": "2019-05-10T02:05:15.982413+00:00", "pullrequest": {"type": "pullrequest", "id": 63, "links": {"self": {"href": "data/repositories/labscript_suite/lyse/pullrequests/63.json"}, "html": {"href": "#!/labscript_suite/lyse/pull-requests/63"}}, "title": "Fix two issues with delayed closing of lyse"}, "user": {"display_name": "Russell Anderson", "uuid": "{6c12ac6e-1980-466d-86fe-6c163bd116c2}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B6c12ac6e-1980-466d-86fe-6c163bd116c2%7D"}, "html": {"href": "https://bitbucket.org/%7B6c12ac6e-1980-466d-86fe-6c163bd116c2%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:443e4cd1-86c9-4cd5-8034-22bab14d9d1e/e307ce36-5fb6-4418-8090-b9e533eab225/128"}}, "nickname": "rpanderson", "type": "user", "account_id": "557058:443e4cd1-86c9-4cd5-8034-22bab14d9d1e"}}, "pull_request": {"type": "pullrequest", "id": 63, "links": {"self": {"href": "data/repositories/labscript_suite/lyse/pullrequests/63.json"}, "html": {"href": "#!/labscript_suite/lyse/pull-requests/63"}}, "title": "Fix two issues with delayed closing of lyse"}}, {"update": {"description": "Fix two issues with delayed closing of lyse\r\n\r\n* There was a bug where if no configuration changed, Lyse.on_close_event\r\n  would not terminate the subprocesses, and then it would wait the full\r\n  two seconds before quitting (and potentially leave any non-zprocess subprocesses\r\n  running). Refactored on_close_event(), factoring out the 'are you sure' dialog\r\n  and the termination of all subprocesses into separate functions while fixing\r\n  the logic here.\r\n* When lyse was to actually quit, it called qapplication.quit() instead of .close()\r\n  on the main window. This means if running with `python -i`, lyse doesn't actually\r\n  close, as the event loop just fires back up again. Now it actally calls close(),\r\n  and this triggers the same method that caught the first close event, which knows\r\n  it's the second time it's been called because a flag has been set so actually closes.\r\n  This also has the side effect that the user clicking close twice will close\r\n  lyse regardless of the timeout (which seems fine).", "title": "Fix two issues with delayed closing of lyse", "destination": {"commit": {"hash": "e8dda2f57f68", "type": "commit", "links": {"self": {"href": "data/repositories/labscript_suite/lyse/commit/e8dda2f57f68.json"}, "html": {"href": "#!/labscript_suite/lyse/commits/e8dda2f57f68"}}}, "repository": {"links": {"self": {"href": "data/repositories/labscript_suite/lyse.json"}, "html": {"href": "#!/labscript_suite/lyse"}, "avatar": {"href": "data/bytebucket.org/ravatar/{55eebdfe-43d1-4ae8-9049-50c55b295397}ts=249921"}}, "type": "repository", "name": "lyse", "full_name": "labscript_suite/lyse", "uuid": "{55eebdfe-43d1-4ae8-9049-50c55b295397}"}, "branch": {"name": "default"}}, "reason": "", "source": {"commit": {"hash": "efe00aa15132", "type": "commit", "links": {"self": {"href": "https://api.bitbucket.org/2.0/repositories/cbillington/lyse/commit/efe00aa15132"}, "html": {"href": "#!/cbillington/lyse/commits/efe00aa15132"}}}, "repository": {"links": {"self": {"href": "https://api.bitbucket.org/2.0/repositories/cbillington/lyse"}, "html": {"href": "#!/cbillington/lyse"}, "avatar": {"href": "data/bytebucket.org/ravatar/{47c91022-279d-4058-88a8-959fe9ffb409}ts=python"}}, "type": "repository", "name": "lyse", "full_name": "cbillington/lyse", "uuid": "{47c91022-279d-4058-88a8-959fe9ffb409}"}, "branch": {"name": "bugfix"}}, "state": "OPEN", "author": {"display_name": "Chris Billington", "uuid": "{e363c5a9-5075-4656-afb5-88bd6a6dceeb}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D"}, "html": {"href": "https://bitbucket.org/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/9238baf7300c41c0e7294db922899e6ad=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsCB-1.png"}}, "nickname": "cbillington", "type": "user", "account_id": "557058:cbf1bc43-1dc2-477b-9e25-1a8f40fd7ee3"}, "date": "2019-05-10T01:13:27.035866+00:00"}, "pull_request": {"type": "pullrequest", "id": 63, "links": {"self": {"href": "data/repositories/labscript_suite/lyse/pullrequests/63.json"}, "html": {"href": "#!/labscript_suite/lyse/pull-requests/63"}}, "title": "Fix two issues with delayed closing of lyse"}}, {"update": {"description": "Fix two issues with delayed closing of lyse\r\n\r\n* There was a bug where if no configuration changed, Lyse.on_close_event\r\n  would not terminate the subprocesses, and then it would wait the full\r\n  two seconds before quitting (and potentially leave any non-zprocess subprocesses\r\n  running). Refactored on_close_event(), factoring out the 'are you sure' dialog\r\n  and the termination of all subprocesses into separate functions while fixing\r\n  the logic here.\r\n* When lyse was to actually quit, it called qapplication.quit() instead of .close()\r\n  on the main window. This means if running with `python -i`, lyse doesn't actually\r\n  close, as the event loop just fires back up again. Now it actally calls close(),\r\n  and this triggers the same method that caught the first close event, which knows\r\n  it's the second time it's been called because a flag has been set so actually closes.\r\n  This also has the side effect that the user clicking close twice will close\r\n  lyse regardless of the timeout (which seems fine).", "title": "Fix two issues with delayed closing of lyse", "destination": {"commit": {"hash": "e8dda2f57f68", "type": "commit", "links": {"self": {"href": "data/repositories/labscript_suite/lyse/commit/e8dda2f57f68.json"}, "html": {"href": "#!/labscript_suite/lyse/commits/e8dda2f57f68"}}}, "repository": {"links": {"self": {"href": "data/repositories/labscript_suite/lyse.json"}, "html": {"href": "#!/labscript_suite/lyse"}, "avatar": {"href": "data/bytebucket.org/ravatar/{55eebdfe-43d1-4ae8-9049-50c55b295397}ts=249921"}}, "type": "repository", "name": "lyse", "full_name": "labscript_suite/lyse", "uuid": "{55eebdfe-43d1-4ae8-9049-50c55b295397}"}, "branch": {"name": "default"}}, "reason": "", "source": {"commit": {"hash": "efe00aa15132", "type": "commit", "links": {"self": {"href": "https://api.bitbucket.org/2.0/repositories/cbillington/lyse/commit/efe00aa15132"}, "html": {"href": "#!/cbillington/lyse/commits/efe00aa15132"}}}, "repository": {"links": {"self": {"href": "https://api.bitbucket.org/2.0/repositories/cbillington/lyse"}, "html": {"href": "#!/cbillington/lyse"}, "avatar": {"href": "data/bytebucket.org/ravatar/{47c91022-279d-4058-88a8-959fe9ffb409}ts=python"}}, "type": "repository", "name": "lyse", "full_name": "cbillington/lyse", "uuid": "{47c91022-279d-4058-88a8-959fe9ffb409}"}, "branch": {"name": "bugfix"}}, "state": "OPEN", "author": {"display_name": "Chris Billington", "uuid": "{e363c5a9-5075-4656-afb5-88bd6a6dceeb}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D"}, "html": {"href": "https://bitbucket.org/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/9238baf7300c41c0e7294db922899e6ad=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsCB-1.png"}}, "nickname": "cbillington", "type": "user", "account_id": "557058:cbf1bc43-1dc2-477b-9e25-1a8f40fd7ee3"}, "date": "2019-05-10T01:13:26.982779+00:00"}, "pull_request": {"type": "pullrequest", "id": 63, "links": {"self": {"href": "data/repositories/labscript_suite/lyse/pullrequests/63.json"}, "html": {"href": "#!/labscript_suite/lyse/pull-requests/63"}}, "title": "Fix two issues with delayed closing of lyse"}}]}