{"links": {"self": {"href": "data/repositories/labscript_suite/labscript_utils/pullrequests/85/comments/103194773.json"}, "html": {"href": "#!/labscript_suite/labscript_utils/pull-requests/85/_/diff#comment-103194773"}}, "deleted": false, "pullrequest": {"type": "pullrequest", "id": 85, "links": {"self": {"href": "data/repositories/labscript_suite/labscript_utils/pullrequests/85.json"}, "html": {"href": "#!/labscript_suite/labscript_utils/pull-requests/85"}}, "title": "Add fix_shortcuts() function and catch DLL load error"}, "content": {"raw": "Hey,\n\nI hoped that this would remove an error we faced recently when updating labscript: Python crashes when starting blacs. The crash occurs after blacs the info message \u201cBLACS instantiated\u201d. It says the module causing the error is Qt5Widgets.dll. I will add some pics from the windows error message.\n\nBefore it was that the error occurred first when clicking on the tab of a specific NI\\_card. Python crashed only for one DO-card out \\(not for the other DO-card and not for any other NI-card\\). But after a restart the error changed to what I wrote above.\n\nActually, we had this error on a second experiment computer as well but on this one I somehow managed to get around it \\(probably by restarting the computer\\)\n\nSo one the second computer the problem stays and blacs does not launch anymore.\n\n![](data/bitbucket.org/repo/xg9BdE/images/2822184549-DSC_2312.JPG)\n![](data/bitbucket.org/repo/xg9BdE/images/1331840835-DSC_2311.JPG)\n![](data/bitbucket.org/repo/xg9BdE/images/3033597980-DSC_2313.JPG)\n", "markup": "markdown", "html": "<p>Hey,</p>\n<p>I hoped that this would remove an error we faced recently when updating labscript: Python crashes when starting blacs. The crash occurs after blacs the info message \u201cBLACS instantiated\u201d. It says the module causing the error is Qt5Widgets.dll. I will add some pics from the windows error message.</p>\n<p>Before it was that the error occurred first when clicking on the tab of a specific NI_card. Python crashed only for one DO-card out (not for the other DO-card and not for any other NI-card). But after a restart the error changed to what I wrote above.</p>\n<p>Actually, we had this error on a second experiment computer as well but on this one I somehow managed to get around it (probably by restarting the computer)</p>\n<p>So one the second computer the problem stays and blacs does not launch anymore.</p>\n<p><img alt=\"\" src=\"data/bitbucket.org/repo/xg9BdE/images/2822184549-DSC_2312.JPG\" />\n<img alt=\"\" src=\"data/bitbucket.org/repo/xg9BdE/images/1331840835-DSC_2311.JPG\" />\n<img alt=\"\" src=\"data/bitbucket.org/repo/xg9BdE/images/3033597980-DSC_2313.JPG\" /></p>", "type": "rendered"}, "created_on": "2019-05-23T16:26:40.652372+00:00", "user": {"display_name": "Lars Kohfahl", "uuid": "{14b59397-cbc0-4d8c-8a4a-fe99fb4d2d4a}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B14b59397-cbc0-4d8c-8a4a-fe99fb4d2d4a%7D"}, "html": {"href": "https://bitbucket.org/%7B14b59397-cbc0-4d8c-8a4a-fe99fb4d2d4a%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/630642264cd55e22515678a3a0489ac7d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsLK-2.png"}}, "nickname": "lkohfahl", "type": "user", "account_id": "5aafc5d11396802a57aa7f3b"}, "updated_on": "2019-05-23T16:26:40.959409+00:00", "type": "pullrequest_comment", "id": 103194773}