{"links": {"self": {"href": "data/repositories/labscript_suite/blacs/issues/2/comments/12642056.json"}, "html": {"href": "#!/labscript_suite/blacs/issues/2#comment-12642056"}}, "issue": {"links": {"self": {"href": "data/repositories/labscript_suite/blacs/issues/2.json"}}, "type": "issue", "id": 2, "repository": {"links": {"self": {"href": "data/repositories/labscript_suite/blacs.json"}, "html": {"href": "#!/labscript_suite/blacs"}, "avatar": {"href": "data/bytebucket.org/ravatar/{50ed1eb9-8c1b-4afe-a8b8-8e0a33b39a05}ts=249915"}}, "type": "repository", "name": "BLACS", "full_name": "labscript_suite/blacs", "uuid": "{50ed1eb9-8c1b-4afe-a8b8-8e0a33b39a05}"}, "title": "\"Address in use\" error when restarting"}, "content": {"raw": "I think this snippet might be what it comes down to:\n\n```\n#!python\n\nfrom zprocess import ZMQServer\n\nclass  MyServer(ZMQServer):\n    pass\n\nif __name__ == '__main__':\n    server = MyServer(9999)\n    server.shutdown()\n    server = MyServer(9999)\n\n```\n\nCould you test if this raises the same exception for you Martijn? If it does it means there's something wrong with either PyZMQ or my shutting down code. I can see that my shutting down code does have a race condition, which I will fix, and it would be good to see if this fixes your problem.\n\nPhil I also think there is a race condition in BLACS restarting (which would be there even if the shutting down had no race of its own), I know you have a delay in there to mitigate it, but I have moved the line `experiment_server.shutdown()` to within `BLACSWindow.closeEvent`, such that it happens before the `subprocess.Popen()` that launches the new instance of BLACS. Once I fix my own race condition, any remaining issues are more likely to be the library or OS's fault.", "markup": "markdown", "html": "<p>I think this snippet might be what it comes down to:</p>\n<div class=\"codehilite language-python\"><pre><span></span><span class=\"kn\">from</span> <span class=\"nn\">zprocess</span> <span class=\"kn\">import</span> <span class=\"n\">ZMQServer</span>\n\n<span class=\"k\">class</span>  <span class=\"nc\">MyServer</span><span class=\"p\">(</span><span class=\"n\">ZMQServer</span><span class=\"p\">):</span>\n    <span class=\"k\">pass</span>\n\n<span class=\"k\">if</span> <span class=\"vm\">__name__</span> <span class=\"o\">==</span> <span class=\"s1\">&#39;__main__&#39;</span><span class=\"p\">:</span>\n    <span class=\"n\">server</span> <span class=\"o\">=</span> <span class=\"n\">MyServer</span><span class=\"p\">(</span><span class=\"mi\">9999</span><span class=\"p\">)</span>\n    <span class=\"n\">server</span><span class=\"o\">.</span><span class=\"n\">shutdown</span><span class=\"p\">()</span>\n    <span class=\"n\">server</span> <span class=\"o\">=</span> <span class=\"n\">MyServer</span><span class=\"p\">(</span><span class=\"mi\">9999</span><span class=\"p\">)</span>\n</pre></div>\n\n\n<p>Could you test if this raises the same exception for you Martijn? If it does it means there's something wrong with either PyZMQ or my shutting down code. I can see that my shutting down code does have a race condition, which I will fix, and it would be good to see if this fixes your problem.</p>\n<p>Phil I also think there is a race condition in BLACS restarting (which would be there even if the shutting down had no race of its own), I know you have a delay in there to mitigate it, but I have moved the line <code>experiment_server.shutdown()</code> to within <code>BLACSWindow.closeEvent</code>, such that it happens before the <code>subprocess.Popen()</code> that launches the new instance of BLACS. Once I fix my own race condition, any remaining issues are more likely to be the library or OS's fault.</p>", "type": "rendered"}, "created_on": "2014-09-30T02:51:49.879783+00:00", "user": {"display_name": "Chris Billington", "uuid": "{e363c5a9-5075-4656-afb5-88bd6a6dceeb}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D"}, "html": {"href": "https://bitbucket.org/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/9238baf7300c41c0e7294db922899e6ad=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsCB-1.png"}}, "nickname": "cbillington", "type": "user", "account_id": "557058:cbf1bc43-1dc2-477b-9e25-1a8f40fd7ee3"}, "updated_on": null, "type": "issue_comment", "id": 12642056}