{"links": {"self": {"href": "data/repositories/labscript_suite/lyse/issues/20/comments/37411107.json"}, "html": {"href": "#!/labscript_suite/lyse/issues/20#comment-37411107"}}, "issue": {"links": {"self": {"href": "data/repositories/labscript_suite/lyse/issues/20.json"}}, "type": "issue", "id": 20, "repository": {"links": {"self": {"href": "data/repositories/labscript_suite/lyse.json"}, "html": {"href": "#!/labscript_suite/lyse"}, "avatar": {"href": "data/bytebucket.org/ravatar/{55eebdfe-43d1-4ae8-9049-50c55b295397}ts=249921"}}, "type": "repository", "name": "lyse", "full_name": "labscript_suite/lyse", "uuid": "{55eebdfe-43d1-4ae8-9049-50c55b295397}"}, "title": "Incompatibilities with pandas 0.20.1"}, "content": {"raw": "Thanks for testing David, I'll merge the pull request, and have changed .ix to .iloc.", "markup": "markdown", "html": "<p>Thanks for testing David, I'll merge the pull request, and have changed .ix to .iloc.</p>", "type": "rendered"}, "created_on": "2017-06-06T18:08:57.430663+00:00", "user": {"display_name": "Chris Billington", "uuid": "{e363c5a9-5075-4656-afb5-88bd6a6dceeb}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D"}, "html": {"href": "https://bitbucket.org/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/9238baf7300c41c0e7294db922899e6ad=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsCB-1.png"}}, "nickname": "cbillington", "type": "user", "account_id": "557058:cbf1bc43-1dc2-477b-9e25-1a8f40fd7ee3"}, "updated_on": null, "type": "issue_comment", "id": 37411107}