{"links": {"self": {"href": "data/repositories/labscript_suite/labscript_devices/pullrequests/42/comments/81225428.json"}, "html": {"href": "#!/labscript_suite/labscript_devices/pull-requests/42/_/diff#comment-81225428"}}, "deleted": false, "pullrequest": {"type": "pullrequest", "id": 42, "links": {"self": {"href": "data/repositories/labscript_suite/labscript_devices/pullrequests/42.json"}, "html": {"href": "#!/labscript_suite/labscript_devices/pull-requests/42"}}, "title": "Python3 Novatech"}, "content": {"raw": "Ok, merge conflicts resolved. Also fixed two bugs I saw. `socket` was not imported which would have caused a NameError on `socket.timeout` if `check_remote_values` timed out, and there was a bytestring being included in an error message without being `.decode()`'d, that would have failed too. ", "markup": "markdown", "html": "<p>Ok, merge conflicts resolved. Also fixed two bugs I saw. <code>socket</code> was not imported which would have caused a NameError on <code>socket.timeout</code> if <code>check_remote_values</code> timed out, and there was a bytestring being included in an error message without being <code>.decode()</code>'d, that would have failed too. </p>", "type": "rendered"}, "created_on": "2018-11-02T17:17:14.267571+00:00", "user": {"display_name": "Chris Billington", "uuid": "{e363c5a9-5075-4656-afb5-88bd6a6dceeb}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D"}, "html": {"href": "https://bitbucket.org/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/9238baf7300c41c0e7294db922899e6ad=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsCB-1.png"}}, "nickname": "cbillington", "type": "user", "account_id": "557058:cbf1bc43-1dc2-477b-9e25-1a8f40fd7ee3"}, "updated_on": "2018-11-02T17:17:14.278625+00:00", "type": "pullrequest_comment", "id": 81225428}