{"rendered": {"message": {"raw": "Fixed bug where figure manager cleanup was not done if the analysis script raised an exception\n\nThis bug could lead to hundreds (or thousands) or windows being created if a script which creates one or more figures before crashing was run multiple times before the error in the script was fixed. This is a particular problem for multishot analysis scripts as the exception does not pause analysis execution (FYI I don't think we would want it to pause analysis on multishot errors, the current behaviour in this regard is correct).\n\nThe fix is to place the figure manager cleanup code in a \"finally\" block of a try/except statement so that it is always run regardless of whether the script succesfully made all of the intended figures or not. Any exceptions are still raised as before, and is not handled by the new try/except/finally block.", "markup": "markdown", "html": "<p>Fixed bug where figure manager cleanup was not done if the analysis script raised an exception</p>\n<p>This bug could lead to hundreds (or thousands) or windows being created if a script which creates one or more figures before crashing was run multiple times before the error in the script was fixed. This is a particular problem for multishot analysis scripts as the exception does not pause analysis execution (FYI I don't think we would want it to pause analysis on multishot errors, the current behaviour in this regard is correct).</p>\n<p>The fix is to place the figure manager cleanup code in a \"finally\" block of a try/except statement so that it is always run regardless of whether the script succesfully made all of the intended figures or not. Any exceptions are still raised as before, and is not handled by the new try/except/finally block.</p>", "type": "rendered"}}, "hash": "82e021871a706a3e49bcaa915fd7b79f7994ca3a", "repository": {"links": {"self": {"href": "data/repositories/spielman/lyse_mainline.json"}, "html": {"href": "#!/spielman/lyse_mainline"}, "avatar": {"href": "data/bytebucket.org/ravatar/{7a1eb7ee-a93c-4dc3-9382-4b25819d4342}ts=python"}}, "type": "repository", "name": "lyse_mainline", "full_name": "spielman/lyse_mainline", "uuid": "{7a1eb7ee-a93c-4dc3-9382-4b25819d4342}"}, "links": {"self": {"href": "data/repositories/spielman/lyse_mainline/commit/82e021871a706a3e49bcaa915fd7b79f7994ca3a.json"}, "comments": {"href": "data/repositories/spielman/lyse_mainline/commit/82e021871a706a3e49bcaa915fd7b79f7994ca3a/comments_page=1.json"}, "patch": {"href": "https://api.bitbucket.org/2.0/repositories/spielman/lyse_mainline/patch/82e021871a706a3e49bcaa915fd7b79f7994ca3a"}, "html": {"href": "#!/spielman/lyse_mainline/commits/82e021871a706a3e49bcaa915fd7b79f7994ca3a"}, "diff": {"href": "https://api.bitbucket.org/2.0/repositories/spielman/lyse_mainline/diff/82e021871a706a3e49bcaa915fd7b79f7994ca3a"}, "approve": {"href": "https://api.bitbucket.org/2.0/repositories/spielman/lyse_mainline/commit/82e021871a706a3e49bcaa915fd7b79f7994ca3a/approve"}, "statuses": {"href": "data/repositories/spielman/lyse_mainline/commit/82e021871a706a3e49bcaa915fd7b79f7994ca3a/statuses_page=1.json"}}, "author": {"raw": "pstarkey", "type": "author", "user": {"display_name": "Philip Starkey", "uuid": "{48af65db-e5fc-459c-a7eb-52eb1f9a5690}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B48af65db-e5fc-459c-a7eb-52eb1f9a5690%7D"}, "html": {"href": "https://bitbucket.org/%7B48af65db-e5fc-459c-a7eb-52eb1f9a5690%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/dc318537facc47ebe1ae98a7aabacecfd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsPS-0.png"}}, "nickname": "pstarkey", "type": "user", "account_id": "557058:52a111e4-40da-4441-9143-417f95f2db97"}}, "summary": {"raw": "Fixed bug where figure manager cleanup was not done if the analysis script raised an exception\n\nThis bug could lead to hundreds (or thousands) or windows being created if a script which creates one or more figures before crashing was run multiple times before the error in the script was fixed. This is a particular problem for multishot analysis scripts as the exception does not pause analysis execution (FYI I don't think we would want it to pause analysis on multishot errors, the current behaviour in this regard is correct).\n\nThe fix is to place the figure manager cleanup code in a \"finally\" block of a try/except statement so that it is always run regardless of whether the script succesfully made all of the intended figures or not. Any exceptions are still raised as before, and is not handled by the new try/except/finally block.", "markup": "markdown", "html": "<p>Fixed bug where figure manager cleanup was not done if the analysis script raised an exception</p>\n<p>This bug could lead to hundreds (or thousands) or windows being created if a script which creates one or more figures before crashing was run multiple times before the error in the script was fixed. This is a particular problem for multishot analysis scripts as the exception does not pause analysis execution (FYI I don't think we would want it to pause analysis on multishot errors, the current behaviour in this regard is correct).</p>\n<p>The fix is to place the figure manager cleanup code in a \"finally\" block of a try/except statement so that it is always run regardless of whether the script succesfully made all of the intended figures or not. Any exceptions are still raised as before, and is not handled by the new try/except/finally block.</p>", "type": "rendered"}, "participants": [], "parents": [{"hash": "632a9047c972d6514e88c91b1b13e2d180074884", "type": "commit", "links": {"self": {"href": "data/repositories/spielman/lyse_mainline/commit/632a9047c972d6514e88c91b1b13e2d180074884.json"}, "html": {"href": "#!/spielman/lyse_mainline/commits/632a9047c972d6514e88c91b1b13e2d180074884"}}}], "date": "2014-10-02T07:18:27+00:00", "message": "Fixed bug where figure manager cleanup was not done if the analysis script raised an exception\n\nThis bug could lead to hundreds (or thousands) or windows being created if a script which creates one or more figures before crashing was run multiple times before the error in the script was fixed. This is a particular problem for multishot analysis scripts as the exception does not pause analysis execution (FYI I don't think we would want it to pause analysis on multishot errors, the current behaviour in this regard is correct).\n\nThe fix is to place the figure manager cleanup code in a \"finally\" block of a try/except statement so that it is always run regardless of whether the script succesfully made all of the intended figures or not. Any exceptions are still raised as before, and is not handled by the new try/except/finally block.", "type": "commit", "git_hash": "5c478a0c3de853756e885cda4b32cf2bd8987b1d", "tags": null, "branches": "gtk"}