{"links": {"self": {"href": "data/repositories/labscript_suite/runviewer/issues/18/comments/45044371.json"}, "html": {"href": "#!/labscript_suite/runviewer/issues/18#comment-45044371"}}, "issue": {"links": {"self": {"href": "data/repositories/labscript_suite/runviewer/issues/18.json"}}, "type": "issue", "id": 18, "repository": {"links": {"self": {"href": "data/repositories/labscript_suite/runviewer.json"}, "html": {"href": "#!/labscript_suite/runviewer"}, "avatar": {"href": "data/bytebucket.org/ravatar/{71215673-ad3e-425c-ae04-84cc6c2ca7da}ts=445022"}}, "type": "repository", "name": "runviewer", "full_name": "labscript_suite/runviewer", "uuid": "{71215673-ad3e-425c-ae04-84cc6c2ca7da}"}, "title": "No allowed version of pyqtgraph works 100% correctly with runviewer"}, "content": {"raw": "Also, I am able to reset the x axis on 0.10.0, both with PyQt4 and PyQt5", "markup": "markdown", "html": "<p>Also, I am able to reset the x axis on 0.10.0, both with PyQt4 and PyQt5</p>", "type": "rendered"}, "created_on": "2018-04-30T04:59:25.294125+00:00", "user": {"display_name": "Chris Billington", "uuid": "{e363c5a9-5075-4656-afb5-88bd6a6dceeb}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D"}, "html": {"href": "https://bitbucket.org/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/9238baf7300c41c0e7294db922899e6ad=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsCB-1.png"}}, "nickname": "cbillington", "type": "user", "account_id": "557058:cbf1bc43-1dc2-477b-9e25-1a8f40fd7ee3"}, "updated_on": null, "type": "issue_comment", "id": 45044371}