{"pagelen": 100, "values": [{"links": {"self": {"href": "data/repositories/labscript_suite/runviewer/issues/18/comments/45044204.json"}, "html": {"href": "#!/labscript_suite/runviewer/issues/18#comment-45044204"}}, "issue": {"links": {"self": {"href": "data/repositories/labscript_suite/runviewer/issues/18.json"}}, "type": "issue", "id": 18, "repository": {"links": {"self": {"href": "data/repositories/labscript_suite/runviewer.json"}, "html": {"href": "#!/labscript_suite/runviewer"}, "avatar": {"href": "data/bytebucket.org/ravatar/{71215673-ad3e-425c-ae04-84cc6c2ca7da}ts=445022"}}, "type": "repository", "name": "runviewer", "full_name": "labscript_suite/runviewer", "uuid": "{71215673-ad3e-425c-ae04-84cc6c2ca7da}"}, "title": "No allowed version of pyqtgraph works 100% correctly with runviewer"}, "content": {"raw": "Are you sure this has to do with double import denier? All imports go through it, so if you were to get an importerror you would have gotten anyway, double_import_denier would still be in the traceback even though it is not playing any role.", "markup": "markdown", "html": "<p>Are you sure this has to do with double import denier? All imports go through it, so if you were to get an importerror you would have gotten anyway, double_import_denier would still be in the traceback even though it is not playing any role.</p>", "type": "rendered"}, "created_on": "2018-04-30T04:34:00.357049+00:00", "user": {"display_name": "Chris Billington", "uuid": "{e363c5a9-5075-4656-afb5-88bd6a6dceeb}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D"}, "html": {"href": "https://bitbucket.org/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/9238baf7300c41c0e7294db922899e6ad=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsCB-1.png"}}, "nickname": "cbillington", "type": "user", "account_id": "557058:cbf1bc43-1dc2-477b-9e25-1a8f40fd7ee3"}, "updated_on": null, "type": "issue_comment", "id": 45044204}, {"links": {"self": {"href": "data/repositories/labscript_suite/runviewer/issues/18/comments/45044325.json"}, "html": {"href": "#!/labscript_suite/runviewer/issues/18#comment-45044325"}}, "issue": {"links": {"self": {"href": "data/repositories/labscript_suite/runviewer/issues/18.json"}}, "type": "issue", "id": 18, "repository": {"links": {"self": {"href": "data/repositories/labscript_suite/runviewer.json"}, "html": {"href": "#!/labscript_suite/runviewer"}, "avatar": {"href": "data/bytebucket.org/ravatar/{71215673-ad3e-425c-ae04-84cc6c2ca7da}ts=445022"}}, "type": "repository", "name": "runviewer", "full_name": "labscript_suite/runviewer", "uuid": "{71215673-ad3e-425c-ae04-84cc6c2ca7da}"}, "title": "No allowed version of pyqtgraph works 100% correctly with runviewer"}, "content": {"raw": "I'm not able to reproduce this problem (on Linux, anyway).\n\nI see that pyqtgraph v0.9.10 doesn't work if you have only PyQt5, since it requires PyQt4, resulting in the exception you posted. And if you have both PyQt4 and PyQt5 it breaks with a different ImportError because qtutils goes for PyQt5 first, and pyqtgraph then imports PyQt4 and you can't import both at once.", "markup": "markdown", "html": "<p>I'm not able to reproduce this problem (on Linux, anyway).</p>\n<p>I see that pyqtgraph v0.9.10 doesn't work if you have only PyQt5, since it requires PyQt4, resulting in the exception you posted. And if you have both PyQt4 and PyQt5 it breaks with a different ImportError because qtutils goes for PyQt5 first, and pyqtgraph then imports PyQt4 and you can't import both at once.</p>", "type": "rendered"}, "created_on": "2018-04-30T04:52:55.167836+00:00", "user": {"display_name": "Chris Billington", "uuid": "{e363c5a9-5075-4656-afb5-88bd6a6dceeb}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D"}, "html": {"href": "https://bitbucket.org/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/9238baf7300c41c0e7294db922899e6ad=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsCB-1.png"}}, "nickname": "cbillington", "type": "user", "account_id": "557058:cbf1bc43-1dc2-477b-9e25-1a8f40fd7ee3"}, "updated_on": "2018-04-30T04:53:16.790550+00:00", "type": "issue_comment", "id": 45044325}, {"links": {"self": {"href": "data/repositories/labscript_suite/runviewer/issues/18/comments/45044371.json"}, "html": {"href": "#!/labscript_suite/runviewer/issues/18#comment-45044371"}}, "issue": {"links": {"self": {"href": "data/repositories/labscript_suite/runviewer/issues/18.json"}}, "type": "issue", "id": 18, "repository": {"links": {"self": {"href": "data/repositories/labscript_suite/runviewer.json"}, "html": {"href": "#!/labscript_suite/runviewer"}, "avatar": {"href": "data/bytebucket.org/ravatar/{71215673-ad3e-425c-ae04-84cc6c2ca7da}ts=445022"}}, "type": "repository", "name": "runviewer", "full_name": "labscript_suite/runviewer", "uuid": "{71215673-ad3e-425c-ae04-84cc6c2ca7da}"}, "title": "No allowed version of pyqtgraph works 100% correctly with runviewer"}, "content": {"raw": "Also, I am able to reset the x axis on 0.10.0, both with PyQt4 and PyQt5", "markup": "markdown", "html": "<p>Also, I am able to reset the x axis on 0.10.0, both with PyQt4 and PyQt5</p>", "type": "rendered"}, "created_on": "2018-04-30T04:59:25.294125+00:00", "user": {"display_name": "Chris Billington", "uuid": "{e363c5a9-5075-4656-afb5-88bd6a6dceeb}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D"}, "html": {"href": "https://bitbucket.org/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/9238baf7300c41c0e7294db922899e6ad=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsCB-1.png"}}, "nickname": "cbillington", "type": "user", "account_id": "557058:cbf1bc43-1dc2-477b-9e25-1a8f40fd7ee3"}, "updated_on": null, "type": "issue_comment", "id": 45044371}, {"links": {"self": {"href": "data/repositories/labscript_suite/runviewer/issues/18/comments/45045654.json"}, "html": {"href": "#!/labscript_suite/runviewer/issues/18#comment-45045654"}}, "issue": {"links": {"self": {"href": "data/repositories/labscript_suite/runviewer/issues/18.json"}}, "type": "issue", "id": 18, "repository": {"links": {"self": {"href": "data/repositories/labscript_suite/runviewer.json"}, "html": {"href": "#!/labscript_suite/runviewer"}, "avatar": {"href": "data/bytebucket.org/ravatar/{71215673-ad3e-425c-ae04-84cc6c2ca7da}ts=445022"}}, "type": "repository", "name": "runviewer", "full_name": "labscript_suite/runviewer", "uuid": "{71215673-ad3e-425c-ae04-84cc6c2ca7da}"}, "title": "No allowed version of pyqtgraph works 100% correctly with runviewer"}, "content": {"raw": "Right, sorry. Got confused because I a) forgot this was a new virtualenv that would install pyqt5 by default and b) saw double_import_denier in the traceback (which is ocnfusing but I get why it's there now).\n\nThe actual bug is that you can't reset the time axis if there are enough plots to create the scroll bar, and you scroll down so that the tiny plot at the top (which everything is linked to) is hidden. This is something I think I was aware of before. Thought it had been fixed...I guess not (or it's a regression). Anyway, this issue should be closed because the report makes no sense!", "markup": "markdown", "html": "<p>Right, sorry. Got confused because I a) forgot this was a new virtualenv that would install pyqt5 by default and b) saw double_import_denier in the traceback (which is ocnfusing but I get why it's there now).</p>\n<p>The actual bug is that you can't reset the time axis if there are enough plots to create the scroll bar, and you scroll down so that the tiny plot at the top (which everything is linked to) is hidden. This is something I think I was aware of before. Thought it had been fixed...I guess not (or it's a regression). Anyway, this issue should be closed because the report makes no sense!</p>", "type": "rendered"}, "created_on": "2018-04-30T07:10:07.106080+00:00", "user": {"display_name": "Philip Starkey", "uuid": "{48af65db-e5fc-459c-a7eb-52eb1f9a5690}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B48af65db-e5fc-459c-a7eb-52eb1f9a5690%7D"}, "html": {"href": "https://bitbucket.org/%7B48af65db-e5fc-459c-a7eb-52eb1f9a5690%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/dc318537facc47ebe1ae98a7aabacecfd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsPS-0.png"}}, "nickname": "pstarkey", "type": "user", "account_id": "557058:52a111e4-40da-4441-9143-417f95f2db97"}, "updated_on": null, "type": "issue_comment", "id": 45045654}, {"links": {"self": {"href": "data/repositories/labscript_suite/runviewer/issues/18/comments/45045655.json"}, "html": {"href": "#!/labscript_suite/runviewer/issues/18#comment-45045655"}}, "issue": {"links": {"self": {"href": "data/repositories/labscript_suite/runviewer/issues/18.json"}}, "type": "issue", "id": 18, "repository": {"links": {"self": {"href": "data/repositories/labscript_suite/runviewer.json"}, "html": {"href": "#!/labscript_suite/runviewer"}, "avatar": {"href": "data/bytebucket.org/ravatar/{71215673-ad3e-425c-ae04-84cc6c2ca7da}ts=445022"}}, "type": "repository", "name": "runviewer", "full_name": "labscript_suite/runviewer", "uuid": "{71215673-ad3e-425c-ae04-84cc6c2ca7da}"}, "title": "No allowed version of pyqtgraph works 100% correctly with runviewer"}, "content": {"raw": "I was wrong (see above comment)", "markup": "markdown", "html": "<p>I was wrong (see above comment)</p>", "type": "rendered"}, "created_on": "2018-04-30T07:10:30.904928+00:00", "user": {"display_name": "Philip Starkey", "uuid": "{48af65db-e5fc-459c-a7eb-52eb1f9a5690}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B48af65db-e5fc-459c-a7eb-52eb1f9a5690%7D"}, "html": {"href": "https://bitbucket.org/%7B48af65db-e5fc-459c-a7eb-52eb1f9a5690%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/dc318537facc47ebe1ae98a7aabacecfd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsPS-0.png"}}, "nickname": "pstarkey", "type": "user", "account_id": "557058:52a111e4-40da-4441-9143-417f95f2db97"}, "updated_on": null, "type": "issue_comment", "id": 45045655}, {"links": {"self": {"href": "data/repositories/labscript_suite/runviewer/issues/18/comments/45046148.json"}, "html": {"href": "#!/labscript_suite/runviewer/issues/18#comment-45046148"}}, "issue": {"links": {"self": {"href": "data/repositories/labscript_suite/runviewer/issues/18.json"}}, "type": "issue", "id": 18, "repository": {"links": {"self": {"href": "data/repositories/labscript_suite/runviewer.json"}, "html": {"href": "#!/labscript_suite/runviewer"}, "avatar": {"href": "data/bytebucket.org/ravatar/{71215673-ad3e-425c-ae04-84cc6c2ca7da}ts=445022"}}, "type": "repository", "name": "runviewer", "full_name": "labscript_suite/runviewer", "uuid": "{71215673-ad3e-425c-ae04-84cc6c2ca7da}"}, "title": "No allowed version of pyqtgraph works 100% correctly with runviewer"}, "content": {"raw": "In Python 3 double_import_denier hides itself from tracebacks it's not involved in :). But in Python 2 this isn't possible so we get a few extra frames in the traceback unfortunately.", "markup": "markdown", "html": "<p>In Python 3 double_import_denier hides itself from tracebacks it's not involved in :). But in Python 2 this isn't possible so we get a few extra frames in the traceback unfortunately.</p>", "type": "rendered"}, "created_on": "2018-04-30T07:50:18.883642+00:00", "user": {"display_name": "Chris Billington", "uuid": "{e363c5a9-5075-4656-afb5-88bd6a6dceeb}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D"}, "html": {"href": "https://bitbucket.org/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/9238baf7300c41c0e7294db922899e6ad=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsCB-1.png"}}, "nickname": "cbillington", "type": "user", "account_id": "557058:cbf1bc43-1dc2-477b-9e25-1a8f40fd7ee3"}, "updated_on": null, "type": "issue_comment", "id": 45046148}], "page": 1, "size": 6}