{"links": {"self": {"href": "data/repositories/labscript_suite/lyse/issues/25/comments/37725860.json"}, "html": {"href": "#!/labscript_suite/lyse/issues/25#comment-37725860"}}, "issue": {"links": {"self": {"href": "data/repositories/labscript_suite/lyse/issues/25.json"}}, "type": "issue", "id": 25, "repository": {"links": {"self": {"href": "data/repositories/labscript_suite/lyse.json"}, "html": {"href": "#!/labscript_suite/lyse"}, "avatar": {"href": "data/bytebucket.org/ravatar/{55eebdfe-43d1-4ae8-9049-50c55b295397}ts=249921"}}, "type": "repository", "name": "lyse", "full_name": "labscript_suite/lyse", "uuid": "{55eebdfe-43d1-4ae8-9049-50c55b295397}"}, "title": "Plots don't update after error"}, "content": {"raw": "I'm not able to reproduce this, unfortunately. \n\nI can run this script:\n\n\n```\n#!python\n\nimport lyse\nimport numpy as np\n\nrun = lyse.Run(lyse.path)\nrun.save_result('x', 5)\n\nimport matplotlib.pyplot as plt\n\nx = np.linspace(0,10,100)\nplt.plot(x, np.sin(x)*np.random.rand())\n\nassert False\n\nplt.show()\n\n\n```\nrepeatedly, unpausing analysis each time it pauses due to the `assert False`, and I get plots updating (visibly different because of the `rand()` each time) regardless of whether the `AssertionError` is before or after the call to `plt.show()`.\n\nCould you provide a minimal example that demonstrates the problem?", "markup": "markdown", "html": "<p>I'm not able to reproduce this, unfortunately. </p>\n<p>I can run this script:</p>\n<div class=\"codehilite language-python\"><pre><span></span><span class=\"kn\">import</span> <span class=\"nn\">lyse</span>\n<span class=\"kn\">import</span> <span class=\"nn\">numpy</span> <span class=\"kn\">as</span> <span class=\"nn\">np</span>\n\n<span class=\"n\">run</span> <span class=\"o\">=</span> <span class=\"n\">lyse</span><span class=\"o\">.</span><span class=\"n\">Run</span><span class=\"p\">(</span><span class=\"n\">lyse</span><span class=\"o\">.</span><span class=\"n\">path</span><span class=\"p\">)</span>\n<span class=\"n\">run</span><span class=\"o\">.</span><span class=\"n\">save_result</span><span class=\"p\">(</span><span class=\"s1\">&#39;x&#39;</span><span class=\"p\">,</span> <span class=\"mi\">5</span><span class=\"p\">)</span>\n\n<span class=\"kn\">import</span> <span class=\"nn\">matplotlib.pyplot</span> <span class=\"kn\">as</span> <span class=\"nn\">plt</span>\n\n<span class=\"n\">x</span> <span class=\"o\">=</span> <span class=\"n\">np</span><span class=\"o\">.</span><span class=\"n\">linspace</span><span class=\"p\">(</span><span class=\"mi\">0</span><span class=\"p\">,</span><span class=\"mi\">10</span><span class=\"p\">,</span><span class=\"mi\">100</span><span class=\"p\">)</span>\n<span class=\"n\">plt</span><span class=\"o\">.</span><span class=\"n\">plot</span><span class=\"p\">(</span><span class=\"n\">x</span><span class=\"p\">,</span> <span class=\"n\">np</span><span class=\"o\">.</span><span class=\"n\">sin</span><span class=\"p\">(</span><span class=\"n\">x</span><span class=\"p\">)</span><span class=\"o\">*</span><span class=\"n\">np</span><span class=\"o\">.</span><span class=\"n\">random</span><span class=\"o\">.</span><span class=\"n\">rand</span><span class=\"p\">())</span>\n\n<span class=\"k\">assert</span> <span class=\"bp\">False</span>\n\n<span class=\"n\">plt</span><span class=\"o\">.</span><span class=\"n\">show</span><span class=\"p\">()</span>\n</pre></div>\n\n\n<p>repeatedly, unpausing analysis each time it pauses due to the <code>assert False</code>, and I get plots updating (visibly different because of the <code>rand()</code> each time) regardless of whether the <code>AssertionError</code> is before or after the call to <code>plt.show()</code>.</p>\n<p>Could you provide a minimal example that demonstrates the problem?</p>", "type": "rendered"}, "created_on": "2017-06-20T19:21:32.758258+00:00", "user": {"display_name": "Chris Billington", "uuid": "{e363c5a9-5075-4656-afb5-88bd6a6dceeb}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D"}, "html": {"href": "https://bitbucket.org/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/9238baf7300c41c0e7294db922899e6ad=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsCB-1.png"}}, "nickname": "cbillington", "type": "user", "account_id": "557058:cbf1bc43-1dc2-477b-9e25-1a8f40fd7ee3"}, "updated_on": null, "type": "issue_comment", "id": 37725860}