{"priority": "minor", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/labscript_suite/runmanager.json"}, "html": {"href": "#!/labscript_suite/runmanager"}, "avatar": {"href": "data/bytebucket.org/ravatar/{9b4f21e6-54b0-41ea-8f01-db1919f2f790}ts=249918"}}, "type": "repository", "name": "runmanager", "full_name": "labscript_suite/runmanager", "uuid": "{9b4f21e6-54b0-41ea-8f01-db1919f2f790}"}, "links": {"attachments": {"href": "data/repositories/labscript_suite/runmanager/issues/67/attachments_page=1.json"}, "self": {"href": "data/repositories/labscript_suite/runmanager/issues/67.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/labscript_suite/runmanager/issues/67/watch"}, "comments": {"href": "data/repositories/labscript_suite/runmanager/issues/67/comments_page=1.json"}, "html": {"href": "#!/labscript_suite/runmanager/issues/67/next_sequence_index-not-found-error-using"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/labscript_suite/runmanager/issues/67/vote"}}, "reporter": {"display_name": "David Meyer", "uuid": "{8df655d6-8661-4957-b4ba-669cef19bf2d}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B8df655d6-8661-4957-b4ba-669cef19bf2d%7D"}, "html": {"href": "https://bitbucket.org/%7B8df655d6-8661-4957-b4ba-669cef19bf2d%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/2a4efe81a17e5aeccdbc4ef2ca2cc463d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsDM-0.png"}}, "nickname": "dihm", "type": "user", "account_id": "557058:411f7712-e1fa-438c-b578-0359da2d9f06"}, "title": ".next_sequence_index not found error using pre-sequence index defaults", "component": null, "votes": 0, "watches": 1, "content": {"raw": "Updating to tag 2.4.0 I now get many file not found errors for the .next_sequence_index file when opening and closing runmanager. It also appears that the closing error is preventing runmanager from updating runmanager.ini.\r\n\r\nAlso, my shot output folder gets erased on load. I get the corresponding non-default output folder message, but the reset to default folder button is not available.\r\n\r\nI'm guessing that part of this is just me not understanding how to work with the new sequence_index, but I also thought the idea was to not force people to immediately update to the new scheme so I'm not quite sure what is going on.\r\n\r\nThe opening runmanager traceback (which appears twice) is\r\n```\r\nTraceback (most recent call last):\r\n  File \"C:\\labscript_suite\\runmanager\\__main__.py\", line 1411, in load_the_config_file\r\n    self.load_configuration(autoload_config_file)\r\n  File \"C:\\labscript_suite\\runmanager\\__main__.py\", line 3110, in load_configuration\r\n    default_output_folder = self.get_default_output_folder()\r\n  File \"C:\\Anaconda3\\envs\\labscript\\lib\\site-packages\\qtutils\\invoke_in_main.py\", line 228, in f\r\n    return inmain(fn, *args, **kwargs)\r\n  File \"C:\\Anaconda3\\envs\\labscript\\lib\\site-packages\\qtutils\\invoke_in_main.py\", line 102, in inmain\r\n    return fn(*args, **kwargs)\r\n  File \"C:\\labscript_suite\\runmanager\\__main__.py\", line 2388, in get_default_output_folder\r\n    increment_sequence_index=False,\r\n  File \"C:\\labscript_suite\\runmanager\\__init__.py\", line 663, in new_sequence_details\r\n    sequence_index = next_sequence_index(shot_basedir, now, increment_sequence_index)\r\n  File \"C:\\labscript_suite\\runmanager\\__init__.py\", line 624, in next_sequence_index\r\n    with open(sequence_index_file) as f:\r\nIOError: [Errno 2] No such file or directory: u'C:\\\\Users\\\\Experiment Control\\\\Experiments\\\\RydEIT2\\\\ProbeSweep\\\\.next_sequence_index'\r\n```\r\n\r\nRelevant labconfig is\r\n```\r\n[DEFAULT]\r\nexperiment_shot_storage = %(shared_drive)s\\Experiments\\%(experiment_name)s\r\n[runmanager]\r\nautoload_config_file = %(experiment_shot_storage)s\\runmanager.ini\r\noutput_folder_format = %%Y\\%%m\\%%d\r\n```", "markup": "markdown", "html": "<p>Updating to tag 2.4.0 I now get many file not found errors for the .next_sequence_index file when opening and closing runmanager. It also appears that the closing error is preventing runmanager from updating runmanager.ini.</p>\n<p>Also, my shot output folder gets erased on load. I get the corresponding non-default output folder message, but the reset to default folder button is not available.</p>\n<p>I'm guessing that part of this is just me not understanding how to work with the new sequence_index, but I also thought the idea was to not force people to immediately update to the new scheme so I'm not quite sure what is going on.</p>\n<p>The opening runmanager traceback (which appears twice) is</p>\n<div class=\"codehilite\"><pre><span></span>Traceback (most recent call last):\n  File &quot;C:\\labscript_suite\\runmanager\\__main__.py&quot;, line 1411, in load_the_config_file\n    self.load_configuration(autoload_config_file)\n  File &quot;C:\\labscript_suite\\runmanager\\__main__.py&quot;, line 3110, in load_configuration\n    default_output_folder = self.get_default_output_folder()\n  File &quot;C:\\Anaconda3\\envs\\labscript\\lib\\site-packages\\qtutils\\invoke_in_main.py&quot;, line 228, in f\n    return inmain(fn, *args, **kwargs)\n  File &quot;C:\\Anaconda3\\envs\\labscript\\lib\\site-packages\\qtutils\\invoke_in_main.py&quot;, line 102, in inmain\n    return fn(*args, **kwargs)\n  File &quot;C:\\labscript_suite\\runmanager\\__main__.py&quot;, line 2388, in get_default_output_folder\n    increment_sequence_index=False,\n  File &quot;C:\\labscript_suite\\runmanager\\__init__.py&quot;, line 663, in new_sequence_details\n    sequence_index = next_sequence_index(shot_basedir, now, increment_sequence_index)\n  File &quot;C:\\labscript_suite\\runmanager\\__init__.py&quot;, line 624, in next_sequence_index\n    with open(sequence_index_file) as f:\nIOError: [Errno 2] No such file or directory: u&#39;C:\\\\Users\\\\Experiment Control\\\\Experiments\\\\RydEIT2\\\\ProbeSweep\\\\.next_sequence_index&#39;\n</pre></div>\n\n\n<p>Relevant labconfig is</p>\n<div class=\"codehilite\"><pre><span></span><span class=\"k\">[DEFAULT]</span>\n<span class=\"na\">experiment_shot_storage</span> <span class=\"o\">=</span> <span class=\"s\">%(shared_drive)s\\Experiments\\%(experiment_name)s</span>\n<span class=\"k\">[runmanager]</span>\n<span class=\"na\">autoload_config_file</span> <span class=\"o\">=</span> <span class=\"s\">%(experiment_shot_storage)s\\runmanager.ini</span>\n<span class=\"na\">output_folder_format</span> <span class=\"o\">=</span> <span class=\"s\">%%Y\\%%m\\%%d</span>\n</pre></div>", "type": "rendered"}, "assignee": null, "state": "resolved", "version": null, "edited_on": null, "created_on": "2019-04-18T16:15:59.411020+00:00", "milestone": null, "updated_on": "2019-04-18T18:22:26.440739+00:00", "type": "issue", "id": 67}