{"links": {"self": {"href": "data/repositories/labscript_suite/lyse/pullrequests/31/comments/43049792.json"}, "html": {"href": "#!/labscript_suite/lyse/pull-requests/31/_/diff#comment-43049792"}}, "parent": {"id": 43049511, "links": {"self": {"href": "data/repositories/labscript_suite/lyse/pullrequests/31/comments/43049511.json"}, "html": {"href": "#!/labscript_suite/lyse/pull-requests/31/_/diff#comment-43049511"}}}, "deleted": false, "pullrequest": {"type": "pullrequest", "id": 31, "links": {"self": {"href": "data/repositories/labscript_suite/lyse/pullrequests/31.json"}, "html": {"href": "#!/labscript_suite/lyse/pull-requests/31"}}, "title": "Fix a bug in updating the dataframe"}, "content": {"raw": "everything will not be just fine - but the user can continue at their own peril if they really want to. If the dataframe updating crashed then the Qt model might out of sync with the dataframe, for example. This was my motivation for leaving it as a fatal exception in the past. It's not recoverable since any uncaught exception was unexpected, so who knows what happened.\n\nI would raise a big ugly labscript_utils.excepthook exception so that it definitely looks like an uncaught exception, with a full traceback and some added text saying that 'really, lyse is broken now, continue at your own risk, particularly if you're a developer, but if you're a user probably restart lyse and please report a bug'.\n\nI'll do this now.", "markup": "markdown", "html": "<p>everything will not be just fine - but the user can continue at their own peril if they really want to. If the dataframe updating crashed then the Qt model might out of sync with the dataframe, for example. This was my motivation for leaving it as a fatal exception in the past. It's not recoverable since any uncaught exception was unexpected, so who knows what happened.</p>\n<p>I would raise a big ugly labscript_utils.excepthook exception so that it definitely looks like an uncaught exception, with a full traceback and some added text saying that 'really, lyse is broken now, continue at your own risk, particularly if you're a developer, but if you're a user probably restart lyse and please report a bug'.</p>\n<p>I'll do this now.</p>", "type": "rendered"}, "created_on": "2017-08-17T19:40:13.342032+00:00", "user": {"display_name": "Chris Billington", "uuid": "{e363c5a9-5075-4656-afb5-88bd6a6dceeb}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D"}, "html": {"href": "https://bitbucket.org/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/9238baf7300c41c0e7294db922899e6ad=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsCB-1.png"}}, "nickname": "cbillington", "type": "user", "account_id": "557058:cbf1bc43-1dc2-477b-9e25-1a8f40fd7ee3"}, "updated_on": "2017-08-17T19:40:47.952871+00:00", "type": "pullrequest_comment", "id": 43049792}